
[env]
COLORTERM =  "truecolor"

[font]
size = 16.0
# normal.family = "0xProto Nerd Font"
# normal.family = "Monaspace Neon Light"
normal.family = "MonaspiceNe Nerd Font Mono"
normal.style = "Light"

[window]
decorations = "Buttonless"
opacity = 0.8
blur=true

option_as_alt="Both"

[general]
import = [
  "~/.config/alacritty/rose-pine-moon.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/tokyonight.toml"
]
